### ISSUE TITLE
Project License?

### ISSUE THREAD

**Issue by sofroniewn** [acabrelles/protein-viewer#3]
Hi @acabrelles, this project looks great!

I was interested in reusing the [Spheres visual](https://github.com/acabrelles/protein-viewer/blob/d2a04e408efd5727eb36be1683a66c715ede60fe/Viewer3d/VisPyViewer.py#L1-L137) here inside https://github.com/napari/napari, but noticed that this project doesn't have a license on it. I see that the original code looks to have been inspired by something from @campagnola. Is it possible you can add a license to this repository - anything like an MIT or BSD license would be perfect for us. (I'm not sure if he has this code available under a license I can use somewhere if not).

In general we're having some conversations about maybe one day adding molecular/ protein visualization to napari, if that is something that might be of interest to you!

**Comment by acabrelles** [comment]
Hello there! Thank you for your interest, @sofroniewn. To be honest, even if this project is a few years old, I'm still a bit new to this type of works, I honestly never imagined this code would pick anyone's interest! I'm flattered it'd be considered for something like this, so thank you for making my day with that.

As you may have seen, I lack the etiquette to deal with this type of issue (I'd appreciate some guidance, if that's okay). This was part of a final project for my master's degree, which as a whole is under the Attribution-NonCommercial-ShareAlike 3.0 Spain (CC BY-NC-SA 3.0 ES), but in terms of the lycense of the code, I do not know the extent of it. I am aware that the base code I used was a Spheres Visual Luke created just for this issue after I talked to him personally, but I can't seem to find it. It was an example visual made for his [Vispy](https://github.com/campagnola/vispy) repository!

His code allowed me to make the scatters of spheres freely, I just modified it to make each plot of spheres to match the type of atom/molecule it was refering to.

**Comment by sofroniewn** [comment]
Hi @acabrelles, I've a had fun time playing with the library all morning, it has saved me considerable time already!

I'd like to propose adding a [BSD3 license](https://opensource.org/licenses/BSD-3-Clause) to this repository under your name. This is the same license that vispy uses in its project, and I believe would most align with the spirit of Luke and the vispy development team. It would also be compatible with your CC BY license of your final project.

Having a BSD3 license will make it easy for me to turn the `SpheresVisual` into an upstream PR to vispy so that everyone who uses that project can use it, and also for me to reuse any of this code in napari, which also has a BSD3 license. I just include a copy of the license from this project in the appropriate place in these projects and then it is fine to use the code here.

If it's ok with you I will make a PR adding the license. Thanks again for your great work here!

**Comment by acabrelles** [comment]
Thank you kindly for your help with that, and I am really glad that this library has helped you! I'll be keeping my sights on napari, it looks promising. I wish you the best luck with it!
